[package]
name = "miniserver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
futures-util = "0.3.31"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "rt", "macros"] }
tokio-tungstenite = "0.28.0"
tungstenite = "0.28.0"
